.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GIT\-LFS\-EXT" "1" "September 2017" "" ""
.
.SH "NAME"
\fBgit\-lfs\-ext\fR \- View extension details
.
.SH "SYNOPSIS"
\fBgit lfs ext list\fR [\fIname\fR\.\.\.]
.
.SH "DESCRIPTION"
Git LFS extensions enable the manipulation of files streams during smudge and clean\.
.
.SH "EXAMPLES"
.
.IP "\(bu" 4
List details for all extensions
.
.IP
\fBgit lfs ext\fR \fBgit lfs ext list\fR
.
.IP "\(bu" 4
List details for the specified extensions
.
.IP
\fBgit lfs ext list \'foo\' \'bar\'\fR
.
.IP "" 0
.
.SH "SEE ALSO"
Part of the git\-lfs(1) suite\.
