// Do not edit. Bootstrap copy of /private/tmp/go-20171004-32030-1lwkjbw/go/src/cmd/internal/objabi/zbootstrap.go

//line /private/tmp/go-20171004-32030-1lwkjbw/go/src/cmd/internal/objabi/zbootstrap.go:1
// auto generated by go tool dist

package objabi

import "runtime"

const defaultGOROOT = `/usr/local/Cellar/go/1.9.1/libexec`
const defaultGO386 = `sse2`
const defaultGOARM = `7`
const defaultGOOS = runtime.GOOS
const defaultGOARCH = runtime.GOARCH
const defaultGO_EXTLINK_ENABLED = ``
const version = `go1.9.1`
const stackGuardMultiplier = 1
const goexperiment = ``
