.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GIT\-LFS\-UNINSTALL" "1" "August 2017" "" ""
.
.SH "NAME"
\fBgit\-lfs\-uninstall\fR \- Remove Git LFS configuration
.
.SH "SYNOPSIS"
\fBgit lfs uninstall\fR
.
.SH "DESCRIPTION"
Perform the following actions to remove the Git LFS configuration:
.
.IP "\(bu" 4
Remove the "lfs" clean and smudge filters from the global Git config\.
.
.IP "\(bu" 4
Uninstall the Git LFS pre\-push hook if run from inside a Git repository\.
.
.IP "" 0
.
.SH "SEE ALSO"
git\-lfs\-install(1)\.
.
.P
Part of the git\-lfs(1) suite\.
