.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GIT\-LFS\-TRACK" "1" "August 2017" "" ""
.
.SH "NAME"
\fBgit\-lfs\-track\fR \- View or add Git LFS paths to Git attributes
.
.SH "SYNOPSIS"
\fBgit lfs track\fR [options] [\fIpattern\fR\.\.\.]
.
.SH "DESCRIPTION"
Start tracking the given patterns(s) through Git LFS\. The \fIpattern\fR argument is written to \.gitattributes\. If no paths are provided, simply list the currently\-tracked paths\.
.
.P
The gitattributes documentation \fIhttps://git\-scm\.com/docs/gitattributes\fR states that patterns use the gitignore pattern rules \fIhttps://git\-scm\.com/docs/gitignore\fR to match paths\.
.
.SH "OPTIONS"
.
.IP "\(bu" 4
\fB\-\-verbose\fR \fB\-v\fR: If enabled, have \fBgit lfs track\fR log files which it will touch\. Disabled by default\.
.
.IP "\(bu" 4
\fB\-\-dry\-run\fR \fB\-d\fR: If enabled, have \fBgit lfs track\fR log all actions it would normally take (adding entries to \.gitattributes, touching files on disk, etc) without performing any mutative operations to the disk\.
.
.IP
\fBgit lfs track \-\-dry\-run [files]\fR also implicitly mocks the behavior of passing the \fB\-\-verbose\fR, and will log in greater detail what it is doing\.
.
.IP
Disabled by default\.
.
.IP "\(bu" 4
\fB\-\-lockable\fR \fB\-l\fR Make the paths \'lockable\', meaning they should be locked to edit them, and will be made read\-only in the working copy when not locked\.
.
.IP "\(bu" 4
\fB\-\-not\-lockable\fR Remove the lockable flag from the paths so they are no longer read\-only unless locked\.
.
.IP "\(bu" 4
\fB\-\-no\-modify\-attrs\fR Makes matched entries stat\-dirty so that Git can re\-index files you wish to convert to LFS\. Does not modify any \fB\.gitattributes\fR file(s)\.
.
.IP "" 0
.
.SH "EXAMPLES"
.
.TP
List the patterns that Git LFS is currently tracking:
.
.IP
\fBgit lfs track\fR
.
.TP
Configure Git LFS to track GIF files:
.
.IP
\fBgit lfs track "*\.gif"\fR
.
.TP
Configure Git LFS to track PSD files and make them read\-only unless locked:
.
.IP
\fBgit lfs track \-\-lockable "*\.psd"\fR
.
.SH "SEE ALSO"
git\-lfs\-untrack(1), git\-lfs\-install(1), gitattributes(5)\.
.
.P
Part of the git\-lfs(1) suite\.
