.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GIT\-LFS\-CLONE" "1" "August 2017" "" ""
.
.SH "NAME"
\fBgit\-lfs\-clone\fR \- Efficiently clone a LFS\-enabled repository
.
.SH "SYNOPSIS"
\fBgit lfs clone\fR [git clone options] \fIrepository\fR [\fIdirectory\fR]
.
.SH "DESCRIPTION"
Clone an LFS enabled Git repository more efficiently by disabling LFS during the git clone, then performing a \'git lfs pull\' directly afterwards\.
.
.P
\'git lfs clone\' also installs all of the repo\-level hooks (\.git/hooks) that LFS requires to operate\. If \fB\-\-separate\-git\-dir\fR is given, the hooks will be installed there\.
.
.P
This is faster than a regular \'git clone\' because that will download LFS content using the smudge filter, which is executed individually per file in the working copy\. This is relatively inefficient compared to the batch mode and parallel downloads performed by \'git lfs pull\'\.
.
.SH "OPTIONS"
All options supported by \'git clone\'
.
.TP
\fB\-I\fR \fIpaths\fR \fB\-\-include=\fR\fIpaths\fR
See \fIINCLUDE AND EXCLUDE\fR
.
.TP
\fB\-X\fR \fIpaths\fR \fB\-\-exclude=\fR\fIpaths\fR
See \fIINCLUDE AND EXCLUDE\fR
.
.TP
\fB\-\-skip\-repo\fR
Skip installing repo\-level hooks (\.git/hooks) that LFS requires\. Disabled by default\.
.
.SH "INCLUDE AND EXCLUDE"
You can configure Git LFS to only fetch objects to satisfy references in certain paths of the repo, and/or to exclude certain paths of the repo, to reduce the time you spend downloading things you do not use\.
.
.P
In lfsconfig, set lfs\.fetchinclude and lfs\.fetchexclude to comma\-separated lists of paths to include/exclude in the fetch (wildcard matching as per gitignore)\. Only paths which are matched by fetchinclude and not matched by fetchexclude will have objects fetched for them\.
.
.SH "SEE ALSO"
git\-clone(1), git\-lfs\-pull(1)\.
.
.P
Part of the git\-lfs(1) suite\.
