QT.script.VERSION = 5.9.1
QT.script.name = QtScript
QT.script.module = QtScript
QT.script.libs = $$QT_MODULE_LIB_BASE
QT.script.includes = $$QT_MODULE_LIB_BASE/QtScript.framework/Headers
QT.script.frameworks = $$QT_MODULE_LIB_BASE
QT.script.bins = $$QT_MODULE_BIN_BASE
QT.script.depends = core
QT.script.uses =
QT.script.module_config = v2 lib_bundle
QT.script.DEFINES = QT_SCRIPT_LIB
QT.script.enabled_features =
QT.script.disabled_features =
QT_CONFIG +=
QT_MODULES += script
