.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GIT\-LFS\-PULL" "1" "October 2017" "" ""
.
.SH "NAME"
\fBgit\-lfs\-pull\fR \- Download all Git LFS files for current ref & checkout
.
.SH "SYNOPSIS"
\fBgit lfs pull\fR [options] [\fIremote\fR]
.
.SH "DESCRIPTION"
Download Git LFS objects for the currently checked out ref, and update the working copy with the downloaded content if required\.
.
.P
This is equivalent to running the following 2 commands:
.
.P
git lfs fetch [options] [\fIremote\fR] git lfs checkout
.
.SH "OPTIONS"
.
.TP
\fB\-I\fR \fIpaths\fR \fB\-\-include=\fR\fIpaths\fR
Specify lfs\.fetchinclude just for this invocation; see [INCLUSION & EXCLUSION]
.
.TP
\fB\-X\fR \fIpaths\fR \fB\-\-exclude=\fR\fIpaths\fR
Specify lfs\.fetchexclude just for this invocation; see [INCLUSION & EXCLUSION]
.
.SH "INCLUSION & EXCLUSION"
You can configure Git LFS to only fetch objects to satisfy references in certain paths of the repo, and/or to exclude certain paths of the repo, to reduce the time you spend downloading things you do not use\.
.
.P
In gitconfig, set lfs\.fetchinclude and lfs\.fetchexclude to comma\-separated lists of paths to include/exclude in the fetch (wildcard matching as per gitignore)\. Only paths which are matched by fetchinclude and not matched by fetchexclude will have objects fetched for them\.
.
.SH "DEFAULT REMOTE"
Without arguments, pull downloads from the default remote\. The default remote is the same as for \fBgit pull\fR, i\.e\. based on the remote branch you\'re tracking first, or origin otherwise\.
.
.SH "SEE ALSO"
git\-lfs\-fetch(1), git\-lfs\-checkout(1)\.
.
.P
Part of the git\-lfs(1) suite\.
