.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GIT\-LFS\-FSCK" "1" "October 2017" "" ""
.
.SH "NAME"
\fBgit\-lfs\-fsck\fR \- Check GIT LFS files for consistency
.
.SH "SYNOPSIS"
\fBgit lfs fsck\fR
.
.SH "DESCRIPTION"
Checks all GIT LFS files in the current HEAD for consistency\.
.
.P
Corrupted files are moved to "\.git/lfs/bad"\.
.
.SH "SEE ALSO"
git\-lfs\-ls\-files(1), git\-lfs\-status(1)\.
.
.P
Part of the git\-lfs(1) suite\.
